---
abstract: 'create and use a local lib/ for perl modules with PERL5LIB'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: local-lib
no_index:
  directory:
    - t
    - inc
    - xt
requires:
  CPAN: 1.82
  ExtUtils::Install: 1.43
  ExtUtils::MakeMaker: 6.74
  Module::Build: 0.36
  perl: v5.8.1
resources:
  IRC: irc://irc.perl.org/#local-lib
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=local-lib
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/p5sagit/local-lib.git
version: 2.000_002
