---
abstract: 'create and use a local lib/ for perl modules with PERL5LIB'
author:
  - 'Matt S Trout <mst@shadowcat.co.uk> http://www.shadowcat.co.uk/'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: local-lib
no_index:
  directory:
    - inc
    - t
requires:
  CPAN: 1.80
  ExtUtils::CBuilder: 0
  ExtUtils::MakeMaker: 6.31
  ExtUtils::ParseXS: 0
  Module::Build: 0.28
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.003004
